import { PROMPT_CACHE_MODE_ARGUMENT } from '../cache';
import {
  FLAGS_ARGUMENT,
  MODEL_ARGUMENT,
  REASONING_EFFORT_ARGUMENT,
  SERVICE_TIER_ARGUMENT,
  STREAMING_MODE_ARGUMENT,
  VERBOSITY_ARGUMENT,
} from '../options';

export const API_KEY_ARGUMENT = 'api_key';

// pluginStorage는 전 플러그인 공용 네임스페이스라 접두사가 필수다.
export const ARGUMENT_BACKUP_STORAGE_KEY = 'llm-gateway-provider:arguments-backup';

export type BackedUpArgumentName =
  | typeof API_KEY_ARGUMENT
  | typeof MODEL_ARGUMENT
  | typeof PROMPT_CACHE_MODE_ARGUMENT
  | typeof SERVICE_TIER_ARGUMENT
  | typeof REASONING_EFFORT_ARGUMENT
  | typeof VERBOSITY_ARGUMENT
  | typeof STREAMING_MODE_ARGUMENT
  | typeof FLAGS_ARGUMENT;

export const BACKED_UP_ARGUMENT_NAMES: readonly BackedUpArgumentName[] = [
  API_KEY_ARGUMENT,
  MODEL_ARGUMENT,
  PROMPT_CACHE_MODE_ARGUMENT,
  SERVICE_TIER_ARGUMENT,
  REASONING_EFFORT_ARGUMENT,
  VERBOSITY_ARGUMENT,
  STREAMING_MODE_ARGUMENT,
  FLAGS_ARGUMENT,
];
