import type { ThemeColors } from './types';

// getColorScheme()이 없는 RisuAI 버전에서도 현재 프리셋과 같은 색을 사용한다.
export const PRESET_SCHEMES: Record<string, ThemeColors> = {
  'default':       { bgcolor: '#282a36', darkbg: '#21222c', borderc: '#6272a4', selected: '#44475a', textcolor: '#f8f8f2', textcolor2: '#64748b', darkBorderc: '#4b5563', darkbutton: '#374151' },
  'dark':          { bgcolor: '#1a1a1a', darkbg: '#141414', borderc: '#525252', selected: '#3d3d3d', textcolor: '#f5f5f5', textcolor2: '#a3a3a3', darkBorderc: '#404040', darkbutton: '#2e2e2e' },
  'light':         { bgcolor: '#ffffff', darkbg: '#f0f0f0', borderc: '#0f172a', selected: '#e0e0e0', textcolor: '#0f172a', textcolor2: '#64748b', darkBorderc: '#d1d5db', darkbutton: '#e5e7eb' },
  'cherry':        { bgcolor: '#450a0a', darkbg: '#7f1d1d', borderc: '#ea580c', selected: '#d97706', textcolor: '#f8f8f2', textcolor2: '#fca5a5', darkBorderc: '#92400e', darkbutton: '#b45309' },
  'galaxy':        { bgcolor: '#0f172a', darkbg: '#1f2a48', borderc: '#8be9fd', selected: '#457b9d', textcolor: '#f8f8f2', textcolor2: '#8be9fd', darkBorderc: '#457b9d', darkbutton: '#1f2a48' },
  'nature':        { bgcolor: '#1b4332', darkbg: '#2d6a4f', borderc: '#a8dadc', selected: '#4d908e', textcolor: '#f8f8f2', textcolor2: '#4d908e', darkBorderc: '#457b9d', darkbutton: '#2d6a4f' },
  'realblack':     { bgcolor: '#000000', darkbg: '#000000', borderc: '#6272a4', selected: '#44475a', textcolor: '#f8f8f2', textcolor2: '#64748b', darkBorderc: '#4b5563', darkbutton: '#374151' },
  'monokai-light': { bgcolor: '#f8f8f2', darkbg: '#e8e8e3', borderc: '#75715e', selected: '#d8d8d0', textcolor: '#272822', textcolor2: '#75715e', darkBorderc: '#c0c0b8', darkbutton: '#d0d0c8' },
  'monokai-black': { bgcolor: '#272822', darkbg: '#1e1f1a', borderc: '#75715e', selected: '#3e3d32', textcolor: '#f8f8f2', textcolor2: '#a6a68a', darkBorderc: '#3e3d32', darkbutton: '#3e3d32' },
  'lite':          { bgcolor: '#1f2937', darkbg: '#1c2533', borderc: '#475569', selected: '#475569', textcolor: '#f8f8f2', textcolor2: '#64748b', darkBorderc: '#030712', darkbutton: '#374151' },
};

export const STYLES = [
  '*, *::before, *::after { box-sizing:border-box; }',
  'html { background:transparent; }',
  'body { margin:0; min-height:100vh; display:flex; align-items:center; justify-content:center; padding:20px; background:rgba(0,0,0,.55); color:var(--text); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }',
  '#app { width:min(100%,384px); max-height:calc(100vh - 40px); overflow:auto; border:1px solid var(--border2); border-radius:14px; background:var(--background2); box-shadow:0 16px 48px color-mix(in srgb,var(--text) 18%,transparent); }',
  'form { display:flex; flex-direction:column; }',
  '.settings-content { display:flex; flex-direction:column; gap:12px; padding:20px 18px 18px; }',
  '.field { display:flex; flex-direction:column; gap:6px; min-width:0; }',
  '.field-caption { color:var(--text2); font-size:11px; font-weight:500; letter-spacing:.01em; line-height:1.2; }',
  'input, select { width:100%; height:38px; padding:0 12px; border:1px solid var(--border2); border-radius:8px; outline:none; background:color-mix(in srgb,var(--background) 88%,var(--background2)); color:var(--text); font:inherit; font-size:13px; }',
  'input:focus, select:focus { border-color:var(--accent); box-shadow:0 0 0 2px color-mix(in srgb,var(--accent) 32%,transparent); }',
  // 네이티브 화살표는 우측에 딱 붙어 여백을 줄 수 없어, CSS 그라디언트 셰브런으로
  // 교체한다 (CSP상 외부/data 이미지 대신 그라디언트 사용).
  'select { cursor:pointer; appearance:none; padding-right:34px; background-image:linear-gradient(45deg,transparent 50%,var(--text2) 50%),linear-gradient(135deg,var(--text2) 50%,transparent 50%); background-position:calc(100% - 19px) 55%,calc(100% - 14px) 55%; background-size:5px 5px; background-repeat:no-repeat; }',
  '.secret-control { position:relative; }',
  '.secret-control input { padding-right:46px; letter-spacing:.08em; }',
  '.visibility-toggle { position:absolute; top:7px; right:7px; display:grid; place-items:center; width:30px; height:24px; padding:0; border:0; border-left:1px solid var(--border2); border-radius:0; background:transparent; color:var(--text2); cursor:pointer; }',
  '.visibility-toggle svg { width:16px; height:16px; fill:none; stroke:currentColor; stroke-linecap:round; stroke-linejoin:round; stroke-width:1.6; }',
  '.visibility-toggle .eye-slash { display:none; }',
  '.visibility-toggle[aria-pressed="true"] .eye-slash { display:block; }',
  '.visibility-toggle:focus-visible { outline:2px solid var(--accent); outline-offset:1px; }',
  '.cache-mode-field .field-caption { color:color-mix(in srgb,var(--accent) 70%,var(--text)); }',
  '.cache-mode-field select { border-color:color-mix(in srgb,var(--accent) 75%,var(--border2)); background:color-mix(in srgb,var(--accent) 22%,var(--background)); font-weight:600; }',
  '.toggle-control { position:relative; display:flex; align-items:center; justify-content:space-between; width:100%; height:38px; padding:0 11px 0 12px; border:1px solid var(--border2); border-radius:8px; background:color-mix(in srgb,var(--background) 88%,var(--background2)); color:var(--text2); font-size:13px; cursor:pointer; }',
  '.switch-input { position:absolute; width:1px; height:1px; margin:0; opacity:0; }',
  '.switch-track { position:relative; width:34px; height:20px; flex:0 0 auto; border-radius:999px; background:color-mix(in srgb,var(--border2) 65%,var(--background)); transition:background .16s ease; }',
  '.switch-knob { position:absolute; top:2px; left:2px; width:16px; height:16px; border-radius:50%; background:color-mix(in srgb,var(--text) 20%,var(--background)); box-shadow:0 1px 3px color-mix(in srgb,var(--text) 25%,transparent); transition:transform .16s ease,background .16s ease; }',
  '.switch-input:checked + .switch-track { background:var(--accent); }',
  '.switch-input:checked + .switch-track .switch-knob { transform:translateX(14px); background:var(--background); }',
  '.switch-input:focus-visible + .switch-track { outline:2px solid color-mix(in srgb,var(--accent) 55%,transparent); outline-offset:2px; }',
  '.advanced-divider { display:flex; align-items:center; gap:10px; margin-top:2px; color:var(--text2); font-size:11px; }',
  '.advanced-divider::before, .advanced-divider::after { content:""; height:0; border-top:1px dashed var(--border2); }',
  '.advanced-divider::before { flex:0 0 8px; }',
  '.advanced-divider::after { flex:1; }',
  '.flags { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:8px 10px; margin:0; padding:0; border:0; }',
  '.checkbox { display:flex; align-items:center; gap:7px; min-width:0; font-size:12px; color:var(--text); }',
  '.checkbox input { width:16px; height:16px; flex:0 0 auto; margin:0; padding:0; accent-color:var(--accent); }',
  '.checkbox span { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
  '.checkbox.unsupported { color:var(--text2); opacity:.7; }',
  '.notice { margin:0; padding:8px 10px; border:1px solid var(--accent); border-radius:8px; color:var(--text); font-size:12px; }',
  '.notice[hidden] { display:none; }',
  '.cache-diagnostic { margin:0; color:var(--text2); font-size:.8em; line-height:1.45; }',
  '.cache-diagnostic[hidden] { display:none; }',
  // 모바일에서 설정을 스크롤해도 손익과 닫기 동작에 바로 접근할 수 있게 하단에 고정한다.
  '.settings-footer { position:sticky; z-index:1; bottom:0; display:flex; align-items:center; justify-content:space-between; min-height:56px; padding:10px 16px; border-top:1px solid var(--border2); background:var(--background2); }',
  '.ledger { --popover-background:color-mix(in srgb,var(--text) 90%,var(--background)); position:relative; display:flex; align-items:center; gap:2px; min-width:0; }',
  '.ledger-trigger { display:flex; align-items:center; gap:6px; min-width:0; padding:4px 2px 4px 0; border:0; background:transparent; color:var(--text2); font:inherit; font-size:11px; cursor:pointer; }',
  '.ledger-trigger .amount { font-size:12.5px; font-weight:600; font-variant-numeric:tabular-nums; }',
  '.ledger-trigger:hover, .ledger-trigger:focus-visible { color:var(--text); }',
  '.ledger-trigger:focus-visible { outline:2px solid var(--accent); outline-offset:2px; }',
  '.info-icon { font-size:11px; }',
  '.ledger-popover { position:absolute; z-index:2; bottom:calc(100% + 11px); left:-2px; width:190px; padding:11px 12px; border:1px solid color-mix(in srgb,var(--background) 22%,transparent); border-radius:8px; background:var(--popover-background); color:var(--background); box-shadow:0 10px 28px color-mix(in srgb,var(--text) 24%,transparent); opacity:0; visibility:hidden; transform:translateY(4px); pointer-events:none; transition:opacity .14s ease,visibility .14s ease,transform .14s ease; }',
  '.ledger-popover::after { content:""; position:absolute; top:100%; left:13px; border:6px solid transparent; border-top-color:var(--popover-background); }',
  '.ledger:hover .ledger-popover, .ledger.is-open .ledger-popover { opacity:1; visibility:visible; transform:translateY(0); pointer-events:auto; }',
  '.ledger-detail { display:flex; flex-direction:column; gap:6px; }',
  '.ledger-row { display:flex; justify-content:space-between; gap:12px; font-size:11px; font-variant-numeric:tabular-nums; }',
  '.ledger-result { padding-top:3px; border-top:1px solid color-mix(in srgb,var(--background) 25%,transparent); }',
  '.ledger .amount.gain { color:#4ade80; }',
  '.ledger .amount.loss { color:#f87171; }',
  '.ledger .amount.neutral { color:inherit; }',
  '.ledger-reset { display:grid; place-items:center; width:22px; height:22px; padding:0; border:0; border-radius:5px; background:transparent; color:var(--text2); font:inherit; font-size:15px; line-height:1; cursor:pointer; }',
  '.ledger-reset:hover:not(:disabled), .ledger-reset:focus-visible { color:var(--text); background:color-mix(in srgb,var(--text) 10%,transparent); }',
  '.close-button { min-width:58px; padding:8px 14px; border:1px solid color-mix(in srgb,var(--text) 70%,var(--background)); border-radius:9px; background:color-mix(in srgb,var(--text) 88%,var(--background)); color:var(--background); font:inherit; font-size:12px; font-weight:600; cursor:pointer; }',
  '.close-button:hover:not(:disabled) { background:color-mix(in srgb,var(--text) 78%,var(--background)); }',
  '.close-button:focus-visible { outline:2px solid var(--accent); outline-offset:2px; }',
  'button:disabled { cursor:wait; opacity:.7; }',
  '@media (max-width:420px) { body { padding:10px; } #app { max-height:calc(100vh - 20px); } .settings-content { padding-inline:16px; } }',
].join('\n');
